
#sncalib:
#  class: 'SNCalibrator'
#  avg_frames: 1
#  inputs: { sn: 'slopec.out_slopes' }
#  output_tag: 'auto'
#  tag_template: 'sn_{main.tag}_mod{pyramid.mod_amp}_{TN}'
#  # TN is ignored when looking for existing tags

main_override:
  total_time: 0.002

pyramid_override:
  mod_amp: 20     # These parameters override the ones for pyramid

remove: ['atmo']
# Corresponding outputs are removed automatically
