main_override:
  root_dir:        '/leonardo_work/try25_rossi/MORFEO_DATA0'         # Root directory for calibration manager
  total_time:      0.200
  display_server:  false

# Parallelization over GPUs on a single node

pupilstop_override: { target_rank: 0 }

iir_lift_override: { target_device_idx: 1, target_rank: 1 }

ifunc_m4_override: { target_device_idx: 3, target_rank: 3 }
m2c_m4_override: { target_device_idx: 3, target_rank: 3 }
dm1_override: { target_device_idx: 3, target_rank: 3 }
dm2_override: { target_device_idx: 3, target_rank: 7 }
dm3_override: { target_device_idx: 3, target_rank: 11 }

sh_lgs1_override: { target_device_idx: 0, target_rank: 0 }
sh_lgs2_override: { target_device_idx: 1, target_rank: 1 }
sh_lgs3_override: { target_device_idx: 2, target_rank: 2 }
sh_lgs4_override: { target_device_idx: 0, target_rank: 4 }
sh_lgs5_override: { target_device_idx: 1, target_rank: 5 }
sh_lgs6_override: { target_device_idx: 2, target_rank: 6 }

detector_lgs1_override: { target_device_idx: 0, target_rank: 0 }
detector_lgs2_override: { target_device_idx: 1, target_rank: 1 }
detector_lgs3_override: { target_device_idx: 2, target_rank: 2 }
detector_lgs4_override: { target_device_idx: 0, target_rank: 4 }
detector_lgs5_override: { target_device_idx: 1, target_rank: 5 }
detector_lgs6_override: { target_device_idx: 2, target_rank: 6 }

slopec_lgs1_override: { target_device_idx: 0, target_rank: 0 }
slopec_lgs2_override: { target_device_idx: 1, target_rank: 1 }
slopec_lgs3_override: { target_device_idx: 2, target_rank: 2 }
slopec_lgs4_override: { target_device_idx: 0, target_rank: 4 }
slopec_lgs5_override: { target_device_idx: 1, target_rank: 5 }
slopec_lgs6_override: { target_device_idx: 2, target_rank: 6 }

sh_ngs1_override: { target_device_idx: 0, target_rank: 8 }
sh_ngs2_override: { target_device_idx: 1, target_rank: 9 }
sh_ngs3_override: { target_device_idx: 2, target_rank: 10 }

detector_ngs1_override: { target_device_idx: 0, target_rank: 8 }
detector_ngs2_override: { target_device_idx: 1, target_rank: 9 }
detector_ngs3_override: { target_device_idx: 2, target_rank: 10 }

slopec_ngs1_override: { target_device_idx: 0, target_rank: 8 }
slopec_ngs2_override: { target_device_idx: 1, target_rank: 9 }
slopec_ngs3_override: { target_device_idx: 2, target_rank: 10 }

sh_ref1_override: { target_device_idx: 0, target_rank: 12 }
sh_ref2_override: { target_device_idx: 1, target_rank: 13 }
sh_ref3_override: { target_device_idx: 2, target_rank: 14 }

detector_ref1_override: { target_device_idx: 0, target_rank: 12 }
detector_ref2_override: { target_device_idx: 1, target_rank: 13 }
detector_ref3_override: { target_device_idx: 2, target_rank: 14 }

detector_ref1_override: { target_device_idx: 0, target_rank: 12 }
detector_ref2_override: { target_device_idx: 1, target_rank: 13 }
detector_ref3_override: { target_device_idx: 2, target_rank: 14 }

slopec_ref1_override: { target_device_idx: 0, target_rank: 12 }
slopec_ref2_override: { target_device_idx: 1, target_rank: 13 }
slopec_ref3_override: { target_device_idx: 2, target_rank: 14 }

tomo_ngs_override: { target_device_idx: 3, target_rank: 7 }
iir_ngs_override: { target_device_idx: 3, target_rank: 7 }
iir_focus_override: { target_device_idx: 3, target_rank: 7 }
subtract_ref_override: { target_device_idx: 3, target_rank: 7 }

rec_focus_override: { target_device_idx: 3, target_rank: 11 }

tomo_polc_ref_override: { target_device_idx: 3, target_rank: 15 }
control_ref_override: { target_device_idx: 3, target_rank: 15 }

psf_override: { target_device_idx: 3, target_rank: 15 }

# Workaround for crash bug

#detector_ref1_override: { dt: 0.002 }
#detector_ref2_override: { dt: 0.002 }
#detector_ref3_override: { dt: 0.002 }

subtract_ref_override: { value2_remap_data: 'ref_input_index2.fits' }



